Repository windmill-labs/windmill, pull requests merged in 2023-02, with the labels that each got.

#1140 CLI hints
  frontend/src/lib/components/CliHelpBox.svelte
  frontend/src/lib/components/InlineCodeCopy.svelte
  frontend/src/lib/components/RunForm.svelte
  frontend/src/routes/(root)/(logged)/oauth/callback_slack/+page.svelte
Labels: frontend

#1158 feat: Add workspace webhook
  backend/Cargo.lock
  backend/migrations/20230126023323_webhook.down.sql
  backend/migrations/20230126023323_webhook.up.sql
  backend/sqlx-data.json
  backend/windmill-api/Cargo.toml
  backend/windmill-api/openapi.yaml
  backend/windmill-api/src/apps.rs
  backend/windmill-api/src/flows.rs
  backend/windmill-api/src/folders.rs
  backend/windmill-api/src/lib.rs
  backend/windmill-api/src/resources.rs
  backend/windmill-api/src/scripts.rs
  backend/windmill-api/src/variables.rs
  backend/windmill-api/src/webhook_util.rs
  backend/windmill-api/src/workspaces.rs
  frontend/src/routes/(root)/(logged)/workspace_settings/+page.svelte
Labels: frontend, backend

#1170 chore(main): release 1.62.0
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1183 chore(main): release 1.63.0
  CHANGELOG.md
  version.txt
Labels: autorelease: pending

#1202 chore(main): release 1.63.1
  .github/workflows/change-versions.yml
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/migrations/20230214144244_improve_app_setup.down.sql
  backend/migrations/20230214144244_improve_app_setup.up.sql
  backend/windmill-api/openapi.yaml
  backend/windmill-api/src/oauth2.rs
  backend/windmill-api/src/users.rs
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1205 chore(main): release 1.63.2
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1206 chore(main): release 1.64.0
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1210 chore(main): release 1.65.0
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1214 chore(main): release 1.66.0
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1215 chore(main): release 1.66.1
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1216 chore(main): release 1.67.0
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1219 chore(main): release 1.67.1
  CHANGELOG.md
  version.txt
Labels: autorelease: pending

#1220 chore(main): release 1.67.2
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1221 chore(main): release 1.67.3
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1222 chore(main): release 1.67.4
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1223 chore(main): release 1.68.0
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1226 chore(main): release 1.69.0
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1231 chore(main): release 1.69.1
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1233 chore(main): release 1.69.2
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1236 chore(main): release 1.70.0
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1239 chore(main): release 1.70.1
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending

#1241 chore(main): release 1.70.1
  CHANGELOG.md
Labels: autorelease: pending

#1242 chore(main): release 1.71.0
  CHANGELOG.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/windmill-api/openapi.yaml
  cli/main.ts
  frontend/package-lock.json
  frontend/package.json
  lsp/Pipfile
  openflow.openapi.yaml
  python-client/wmill/pyproject.toml
  python-client/wmill_pg/pyproject.toml
  version.txt
Labels: autorelease: pending
